Numpy Assignment

Theoratical Question:

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

NumPy is a fundamental library in Python for scientific computing. It offers powerful features for working with multidimensional arrays and performing various mathematical operations efficiently.

NumPy (Numerical Python) is an open source Python library that has a wide range of inbuilt functions.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

In [2]:
import numpy as np

In [11]:
a=np.eye(3)

In [12]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.mean(a)

0.3333333333333333

In [14]:
np.average(a)

0.3333333333333333

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

In [4]:
a=np.random.randint(1,8,(4,2))

In [5]:
a

array([[7, 1],
       [5, 3],
       [6, 2],
       [5, 2]])

In [6]:
a.reshape(2,4)

array([[7, 1, 5, 3],
       [6, 2, 5, 2]])

In [8]:
#this is 2D array
a

array([[7, 1],
       [5, 3],
       [6, 2],
       [5, 2]])

In [9]:
#this is 1D array

In [10]:
b=np.zeros(1)

In [11]:
b

array([0.])

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

In [18]:
a=np.random.randint(1,8,(4,2),dtype=int)

In [19]:
a

array([[2, 2],
       [4, 2],
       [3, 2],
       [2, 4]])

Data Types

Data Types: NumPy arrays can hold various data types like integers (int), floats (float), strings (str), etc. You can specify the data type during creation or let NumPy infer it..dtype attribute reveals the data type of the elements in the array

Advantage of Numpy :NumPy is ideal for handling large amounts of homogeneous (same-type) data, offering significant improvements in speed and memory efficiency. It also provides high-level syntax for a wide range of numerical operations, making it a powerful tool for scientific computing and data processing on the CPU.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [17]:
m=np.ones(3)

In [18]:
m

array([1., 1., 1.])

In [19]:
type(m)

numpy.ndarray

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays are multidimensional collections of elements, all of the same data type. Unlike Python lists, NumPy arrays are designed for high-performance operations on large datasets.

Advantage of Numpy :NumPy is ideal for handling large amounts of homogeneous (same-type) data, offering significant improvements in speed and memory efficiency. It also provides high-level syntax for a wide range of numerical operations, making it a powerful tool for scientific computing and data processing on the CPU.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [21]:
str=['i love pwskills']
str.split(",")

AttributeError: 'list' object has no attribute 'split'

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Broadcasting is a mechanism in NumPy that allows performing operations on arrays of different shapes under certain conditions. When operands have different shapes, NumPy expands the smaller array to match the larger one in a specific way to perform element-wise operations.

PRACTICAL QUESTIONS:

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

In [16]:
a=np.random.randint(1,100,size=(3,3))

In [17]:
a

array([[24, 18, 97],
       [28, 91, 13],
       [23,  4, 38]])

In [18]:
a.T

array([[24, 28, 23],
       [18, 91,  4],
       [97, 13, 38]])

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [11]:
b=np.ones(10)

In [12]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
b.reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
b.reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [24]:
import random

In [29]:
c=np.random.rand(4,4)

In [30]:
c

array([[0.66907289, 0.80497703, 0.00183234, 0.67800018],
       [0.86844981, 0.53397402, 0.59786977, 0.41875724],
       [0.88654349, 0.2178634 , 0.85949376, 0.54752472],
       [0.1656474 , 0.65066027, 0.61276418, 0.48245988]])

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [3]:
a=np.arange(10,60,5)

In [4]:
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [5]:
l=['python','numpy','pandas']

In [7]:
e=np.array(l)

In [8]:
e

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [19]:
np.char.upper(e)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [22]:
np.char.capitalize(e)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [23]:
np.char.lower(e)

array(['python', 'numpy', 'pandas'], dtype='<U6')

6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [33]:
string = "Ajay, Bijay, Sanjay"
string.split(",")

['Ajay', ' Bijay', ' Sanjay']

In [34]:
np.array(string.split(","))

array(['Ajay', ' Bijay', ' Sanjay'], dtype='<U7')

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [38]:
f1=np.array([[2,3,4],[5,6,7],[8,9,1]])
f2=np.array([[4,6,2],[7,9,3],[4,2,1]])

In [39]:
f1

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [40]:
f2

array([[4, 6, 2],
       [7, 9, 3],
       [4, 2, 1]])

In [41]:
f1+f2

array([[ 6,  9,  6],
       [12, 15, 10],
       [12, 11,  2]])

In [42]:
f1-f2

array([[-2, -3,  2],
       [-2, -3,  4],
       [ 4,  7,  0]])

In [43]:
f1*f2

array([[ 8, 18,  8],
       [35, 54, 21],
       [32, 18,  1]])

In [45]:
f1/f2

array([[0.5       , 0.5       , 2.        ],
       [0.71428571, 0.66666667, 2.33333333],
       [2.        , 4.5       , 1.        ]])

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [3]:
import numpy.matlib as nm

In [7]:
h=nm.eye(5,dtype=int)

In [8]:
h

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [53]:
g= np.random.randint(1,1000, (10,10))

In [54]:
g

array([[898,  64, 424, 674, 459, 279, 359, 534, 790, 691],
       [331, 489,  36, 587, 213, 145, 253, 948, 694, 146],
       [720,  20, 829, 828, 432,  85, 129, 664, 764, 566],
       [617, 145, 666, 727, 303,  43, 631, 274, 372, 167],
       [ 76, 829, 127, 814, 469, 480, 275, 356, 644, 708],
       [780, 277, 735, 103, 665, 219, 612, 136, 781, 156],
       [635,  97, 326,  27, 600, 900, 965,   3,  46, 805],
       [851, 202, 546, 810, 614, 778, 215, 497, 498,   8],
       [793, 801, 921, 265, 393, 659, 853, 323, 510, 722],
       [795, 174, 356, 363, 306, 575, 615, 512, 660, 817]])

10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [7]:
g=np.random.randint(30,60,size=28)

In [3]:
g

array([52, 53, 39, 51, 36, 42, 35, 45, 39, 38, 52, 38, 48, 44, 41, 43, 54,
       37, 41, 53, 53, 42, 37, 40, 34, 31, 39, 42, 49, 57])

In [8]:
weekly_temperatures=g.reshape(-1,7)

In [9]:
weekly_temperatures

array([[43, 55, 54, 59, 51, 35, 42],
       [45, 37, 47, 41, 34, 52, 44],
       [32, 42, 39, 43, 56, 43, 54],
       [39, 39, 49, 30, 43, 43, 37]])

In [14]:
weekly_averages=np.mean(weekly_temperatures,axis=0)

In [15]:
weekly_averages

array([39.75, 43.25, 47.25, 43.25, 46.  , 43.25, 44.25])